var d = document.getElementById("dibujo");
console.log(d);
var lienzo = d.getContext("2d");
console.log(lienzo);
lienzo.beginPath();
lienzo.strokeStyle = "red";
lienzo.moveTo(0, 0);
lienzo.lineTo(200,200);
lienzo.stroke();
lienzo.closePath();